name: Update Badbits

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:      

permissions:
  contents: write
    
concurrency:
  group: "update-badbits"
  cancel-in-progress: false
      
jobs:
  append-to-badbits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Build Script
        run: go build -o update-badbits ./cmd/denylist-append-from-url/

      - name: Run Script
        run: ./update-badbits public/badbits.deny https://badbits.dwebops.pub/badbits.deny

      - name: Commit Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          if [[ $(git status --porcelain --untracked-files=no) ]]; then
            git add public/badbits.deny
            git commit -m "Append new items to badbits"
            git push origin master
          else
            return 0
          fi

